### ISSUE TITLE
Clicking "Copy" button on code snippets copies undefined

### ISSUE THREAD

**Issue by skfarhat** [bcms/cms#70]
**Describe the bug**
Clicking "Copy" button on code snippets copies undefined whereas 

**To Reproduce**
1. Go to https://docs.thebcms.com/quickstart
2. Click on "Copy"
3. Paste the value
4. See undefined

**Expected behavior**

The actual command to be copied 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by boris-becomes** [comment]
The issue has been [resolved](https://github.com/becomesco/cms-docs/commit/cee75b51a49765c3fc8403c51eb58acb1e2ff0cf).
